from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Dict, Any, List

@dataclass(frozen=True)
class LogEvent:
    """
    Represents a single event extracted from the log stream (JSONL).
    """
    record_id: str
    correlation_id: str
    timestamp: datetime
    event_type: str
    identity: str
    source_ip: str
    payload: Dict[str, Any] = field(default_factory=dict)

@dataclass
class Alert:
    """
    Represents an alert generated by a heuristic after analyzing a timeline of events.
    """
    heuristic_name: str
    severity: str
    description: str
    correlation_id: str
    events: List[LogEvent]
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        """
        Facilitates alert serialization for SIEM forwarding or webhooks.
        """
        return {
            "heuristic": self.heuristic_name,
            "severity": self.severity,
            "description": self.description,
            "correlation_id": self.correlation_id,
            "alert_timestamp": self.timestamp.isoformat(),
            "evidence_record_ids": [e.record_id for e in self.events],
            "trigger_events_count": len(self.events)
        }